### PR TITLE
refactor(core): refactor Button component

### PR DESCRIPTION
**Pull request by nguyenthienthanh**
- Move `ButtonBase` to outside for reuse
- Add `useColorMap` to easily get color by variation
```typescript
const outlineColor = useColorMap<ButtonVariant, ButtonColor>(
    theme,
    {
      text: {
        default: 'rgba(0, 0, 0, 0)',
        primary: 'rgba(0, 0, 0, 0)',
        disabled: 'rgba(0, 0, 0, 0)',
      },
      contained: {
        default: 'rgba(0, 0, 0, 0)',
        primary: 'rgba(0, 0, 0, 0)',
        disabled: 'rgba(0, 0, 0, 0)',
      },
      outlined: {
        default: theme.palette.background.default,
        primary: theme.palette.primary.main,
        disabled: theme.palette.action.disabled,
      },
    },
    props.variant,
    props.color,
    props.disabled,
  )
```

- Add `useSizeMap` to easily get size number from size data
```typescript
const height = useSizeMap<ButtonSize>({ medium: 35, large: 48 }, props.size)
```

### CODE REVIEW

**Comment by duongdev** [comment]
I don't think creating `useColorMap` and `useSizeMap` is a good idea since we only use them INSIDE the `Button` component, no reuse by design. Just make them better utils could be better. @nguyenthienthanh

**Comment by nguyenthienthanh** [comment]
> I don't think creating `useColorMap` and `useSizeMap` is a good idea since we only use them INSIDE the `Button` component, no reuse by design. Just make them better utils could be better. @nguyenthienthanh

We can use them on `CheckBox` component or anything has `variant` and `color` props

**Comment by duongdev** [comment]
@nguyenthienthanh I don't like the way use use `useColorMap` and `useSizeMap`. The original way I used is clearer and esier to understand because it shows the use of `useMemo` hook.

**Comment by duongdev** [comment]
image

I think we should clarify what `S` stands for. Use `Size extends string` instead of only `S extends string`.

**Pull request merged**
